### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by gwillem** [PatDuJour/python-binlist#2]
* Python BINlist version: 0.1.1
* Python version: 2.7.12 and 3.5.2
* Operating System:Ubuntu 16.04 LTS

### Description

```
In [1]: from binlist import BIN
  File "/home/willem/.local/lib/python3.5/site-packages/binlist/network/abstract.py", line 8
    return f'<{resource_name.title()} Network>'
```
```
In [1]: from binlist import BIN
  File "/home/willem/.local/lib/python2.7/site-packages/binlist/network/abstract.py", line 8
    return f'<{resource_name.title()} Network>'
```
Then, I replaced `f''` with `r''` and got:
```
----> 4 class AbstractNetwork(abc.ABC):
      5 
      6     def __repr__(self):

AttributeError: 'module' object has no attribute 'ABC'
```

**Comment by PatDuJour** [comment]
Hi @gwillem sorry the library doesn't support py2.7, that was my mistake to list py2.7 is supported in readme. I don't intent to support py2.7 will retire in 2020

**Comment by gwillem** [comment]
Hi, as you can see, it also does not work on Python 3.5.
